POST http://localhost:5000/Login/signup 
Content-Type: application/json

{
        "username":"arsalanshaikh",
        "city":"karachi",
        "mobilenumber":"03343184497",
        "country":"Pakistan",
        "gender":"Male",
        "industry":"CS",
        "userrole":"user",
        "picture":"https://pixabay.com/photos/sun-water-clouds-reflection-3713835/",
        
        "email":"arsalan1@gmail.com",
        "password":"123456",
        "fullname":"arsalansheikh"
}
#####
POST http://localhost:5000/Login/signin
Content-Type: application/json

{
        "emailorname":"arsalan1@gmail.com",
        "password":"123456"
}
#########
GET http://localhost:5000/profile
#########
GET http://localhost:5000/Learn/

#####
POST http://localhost:5000/Learn/playlist
Content-Type: application/json

{
        "playlisttitle":"Algorithms course"
}


#####
POST http://localhost:5000/Learn/playlist/video
Content-Type: application/json

# Give the proper id after db entry
{
        "id":"1"
}

######

POST http://localhost:5000/Learn/addingresource
Content-Type: application/json

{
        "playlisttitle":"Algorithms course"
}